# Generated by Django 3.2.16 on 2022-10-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221018_1615'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='followed',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
